# This file defines a physical or virtual host.
# It corresponds to your old vm_specs.yaml and parts of defaults.yaml
api_url: "https://pve.homelab.local:8006/api2/json"
node: "pve"
storage_pool: "local-lvm"
network_bridge: "vmbr0"